package com.hotelogix.web;


import org.json.JSONArray;
import org.json.JSONObject;
import org.testng.Assert;

import com.hms.test.RepoterAndCustomException.APIException;

import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.JsonNode;
import com.mashape.unirest.http.Unirest;

public class SaveBooking {

	
	public static String OrderID;
	public static String CancellationCharge;
	public static String OrderAmount;
	public static String DepositTotal;
	public static String depositAmt;
	
	
	
	public void fn_SaveBooking(String url,String wsauth,String firstname,String email) throws APIException{
		try{
			 HttpResponse<JsonNode> response = Unirest.post(url)
		                .header("content-type", "application/json")
		                .header("x-ig-sg", "D_gg%fkl85_j")
		                .header("cache-control", "no-cache")
		                .header("postman-token", "586c8072-4a88-dff1-cb04-294c764db5d7")
		                .body("{ \"hotelogix\": {"
		                		+ "\"version\": \"1.0\","
		                		+ "\"datetime\": \"2015-09-16T11:01:29\","
		                		+ " \"request\": {"
		                		+ " \"method\": \"savebooking\","
		                		+ "\"key\": \""+wsauth+"\","
		                		+ "\"languagecode\" :\"en\","
		                		+ "\"data\": {"
		                		+ "\"guest\": {"
		                		+ "\"fname\": {"
		                		+ "\"value\": \""+firstname+"\""
		                		+ "},"
		                		+ "\"lname\": {"
		                		+ "\"value\": \"Jha\""
		                		+ " },"
		                		+ "\"email\": {"
		                		+ "\"value\": \""+firstname+".hotelogix@stayezee.com\""
		                		+ " },"
		                		+ "\"phone\": {"
		                		+ "\"value\": \"2121221212121\""
		                		+ " },"
		                		+ "\"mobile\": {"
		                		+ "\"value\": \"988888989\""
		                		+ "},"
		                		+ "\"country\": {"
		                		+ "\"code\": \"IN\","
		                		+ "\"value\": \"India\""
		                		+ " },"
		                		+ "\"state\": {"
		                		+ "\"code\": \"UP\","
		                		+ "\"value\": \"noida\""
		                		+ " },"
		                		+ "\"address\": {"
		                		+ " \"value\": \"test address\""
		                		+ " },"
		                		+ "\"city\": {"
		                		+ "\"value\": \"noida\""
		                		+ " },"
		                		+ "\"zip\": {"
		                		+ "\"value\": \"12345A\""
		                		+ " },"
		                		+ "\"taxCode\": {"
		                		+ "\"value\": \"07AQSPJ0999EABC\""
		                		+ "},"
		                		+ "\"workDetail\": {"
		                		+ "\"address\": {"
		                		+ "\"value\": \"work address\""
		                		+ " },"
		                		+ "\"city\": {"
		                		+ "\"value\": \"work city\""
		                		+ "},"
		                		+ "\"state\": {"
		                		+ "\"code\": \"DE\","
		                		+ "\"value\": \"delhi\""
		                		+ " },"
		                		+ "\"country\": {"
		                		+ "\"code\": \"IN\","
		                		+ "\"value\": \"India\""
		                		+ "},"
		                		+ "\"zip\": {"
		                		+ "\"value\": \"110096\""
		                		+ "},"
		                		+ "\"phone\": {"
		                		+ "\"value\": \"123456789\""
		                		+ " },"
		                		+ "\"mobile\": {"
		                		+ "\"value\": \"123456789\""
		                		+ "},"
		                		+ "\"fax\": {"
		                		+ "\"value\": \"123456789\""
		                		+ "}"
		                		+ "}"
		                		+ "},"
		                		+ "\"isGroupBooking\": {"
		                		+ "\"value\":false"
		                		+ "},"
		                		+ "\"hotels\": "
		                		+ "["
		                		+ "{"
		                		+ "\"id\": \""+LoadCart.HotelID+"\","
		                		+ "\"preference\": {"
		                		+ "\"value\": \"nopreference\""
		                		+ "},"
		                		+ "\"bookings\": {"
		                		+ "\"booking\": {"
		                		+ "\"id\": \""+LoadCart.BookingID+"\","
		                		+ "\"gueststays\": "
		                		+ "["
		                		+ "{"
		                		+ "\"id\": \""+LoadCart.GuestStaysID+"\","
		                		+ "\"guest\": {"
		                		+ "\"fname\": {"
		                		+ "\"value\": \""+firstname+"\""
		                		+ " },"
		                		+ "\"lname\": {"
		                		+ "\"value\": \"upadhaya\""
		                		+ "},"
		                		+ "\"email\": {"
		                		+ "\"value\": \""+firstname+".hotelogix@stayezee.com\""
		                		+ "},"
		                		+ "\"phone\": {"
		                		+ "\"value\": \"9968040558\""
		                		+ "},"
		                		+ "\"mobile\": {"
		                		+ "\"value\": \"9968040558\""
		                		+ "},"
		                		+ "\"country\": {"
		                		+ "\"code\": \"IN\","
		                		+ "\"value\": \"India\""
		                		+ "},"
		                		+ "\"state\": {"
		                		+ "\"code\": \"br\","
		                		+ "\"value\": \"Bihar\""
		                		+ "},"
		                		+ "\"address\": {"
		                		+ "\"value\": \"mayur vihar\""
		                		+ "},"
		                		+ "\"city\": {"
		                		+ "\"value\": \"madhubani\""
		                		+ "},"
		                		+ "\"zip\": {"
		                		+ "\"value\": \"110091\""
		                		+ "},"
		                		+ "\"taxCode\": {"
		                		+ "\"value\": \"07AQSPJ0999EABC\""
		                		+ "},"
		                		+ "\"workDetail\": {"
		                		+ "\"address\": {"
		                		+ "\"value\": \"work address\""
		                		+ "},"
		                		+ "\"city\": {"
		                		+ "\"value\": \"work city\""
		                		+ "},"
		                		+ "\"state\": {"
		                		+ "\"code\": \"DE\","
		                		+ "\"value\": \"delhi\""
		                		+ "},"
		                		+ "\"country\": {"
		                		+ "\"code\": \"IN\","
		                		+ "\"value\": \"India\""
		                		+ "},"
		                		+ "\"zip\": {"
		                		+ "\"value\": \"110096\""
		                		+ "},"
		                		+ "\"phone\": {"
		                		+ "\"value\": \"123456789\""
		                		+ "},"
		                		+ "\"mobile\": {"
		                		+ "\"value\": \"123456789\""
		                		+ "},"
		                		+ "\"fax\": {"
		                		+ "\"value\": \"123456789\""
		                		+ "}}}}],"
		                		+ "\"infantstays\": ["
		                		+ "{"
		                		+ "\"id\": \""+LoadCart.InfantID+"\","
		                		+ "\"infant\": {"
		                		+ "\"salutation\": {"
		                		+ "\"value\": \"Mr.\""
		                		+ "},"
		                		+ "\"fname\": {"
		                		+ "\"value\": \"shubham\""
		                		+ " },"
		                		+ "\"lname\": {"
		                		+ "\"value\": \"kumar\""
		                		+ "},"
		                		+ "\"dob\": {"
		                		+ "\"value\": \"2017-08-06 00:00:00\""
		                		+ "}}}]}}}]}}}}")
		                .asJson();
			 JsonNode responseJSONString=response.getBody();
			 Assert.assertEquals(response.getCode(), 200);
			 JSONObject jobj=responseJSONString.getObject();
			 JSONObject hotelogix= jobj.getJSONObject("hotelogix");
			 JSONObject respons=hotelogix.getJSONObject("response");
			 JSONObject order=respons.getJSONObject("order");
			 JSONObject orderamount=order.getJSONObject("orderamount");
			 OrderAmount=orderamount.get("amount").toString();
			 JSONObject bookings=order.getJSONArray("bookings").getJSONObject(0);
			 JSONObject rates=bookings.getJSONArray("rates").getJSONObject(0);
			 JSONObject cancellationpolicies=rates.getJSONArray("cancellationpolicies").getJSONObject(0);
			 CancellationCharge=cancellationpolicies.get("charge").toString();
			 OrderID=order.get("id").toString();
			 JSONObject status= respons.getJSONObject("status");
			 Assert.assertEquals(status.getString("message"), "SUCCESS");
	  }catch(Throwable e){
		  throw new APIException("fn_SaveBooking api is failed", e);	
	  }
	}
	
	
	public void fn_SaveBookingForGroup(String url,String wsauth,String firstname,String email) throws APIException{
		try{
			 HttpResponse<JsonNode> response = Unirest.post(url)
		                .header("content-type", "application/json")
		                .header("x-ig-sg", "D_gg%fkl85_j")
		                .header("cache-control", "no-cache")
		                .header("postman-token", "586c8072-4a88-dff1-cb04-294c764db5d7")
		                .body("{ \"hotelogix\": {"
		                		+ "\"version\": \"1.0\","
		                		+ "\"datetime\": \"2015-09-16T11:01:29\","
		                		+ " \"request\": {"
		                		+ " \"method\": \"savebooking\","
		                		+ "\"key\": \""+wsauth+"\","
		                		+ "\"languagecode\" :\"en\","
		                		+ "\"data\": {"
		                		+ "\"guest\": {"
		                		+ "\"fname\": {"
		                		+ "\"value\": \""+firstname+"\""
		                		+ "},"
		                		+ "\"lname\": {"
		                		+ "\"value\": \"Jha\""
		                		+ " },"
		                		+ "\"email\": {"
		                		+ "\"value\": \""+firstname+".hotelogix@stayezee.com\""
		                		+ " },"
		                		+ "\"phone\": {"
		                		+ "\"value\": \"2121221212121\""
		                		+ " },"
		                		+ "\"mobile\": {"
		                		+ "\"value\": \"988888989\""
		                		+ "},"
		                		+ "\"country\": {"
		                		+ "\"code\": \"IN\","
		                		+ "\"value\": \"India\""
		                		+ " },"
		                		+ "\"state\": {"
		                		+ "\"code\": \"UP\","
		                		+ "\"value\": \"noida\""
		                		+ " },"
		                		+ "\"address\": {"
		                		+ " \"value\": \"test address\""
		                		+ " },"
		                		+ "\"city\": {"
		                		+ "\"value\": \"noida\""
		                		+ " },"
		                		+ "\"zip\": {"
		                		+ "\"value\": \"12345A\""
		                		+ " },"
		                		+ "\"taxCode\": {"
		                		+ "\"value\": \"07AQSPJ0999EABC\""
		                		+ "},"
		                		+ "\"workDetail\": {"
		                		+ "\"address\": {"
		                		+ "\"value\": \"work address\""
		                		+ " },"
		                		+ "\"city\": {"
		                		+ "\"value\": \"work city\""
		                		+ "},"
		                		+ "\"state\": {"
		                		+ "\"code\": \"DE\","
		                		+ "\"value\": \"delhi\""
		                		+ " },"
		                		+ "\"country\": {"
		                		+ "\"code\": \"IN\","
		                		+ "\"value\": \"India\""
		                		+ "},"
		                		+ "\"zip\": {"
		                		+ "\"value\": \"110096\""
		                		+ "},"
		                		+ "\"phone\": {"
		                		+ "\"value\": \"123456789\""
		                		+ " },"
		                		+ "\"mobile\": {"
		                		+ "\"value\": \"123456789\""
		                		+ "},"
		                		+ "\"fax\": {"
		                		+ "\"value\": \"123456789\""
		                		+ "}"
		                		+ "}"
		                		+ "},"
		                		+ "\"isGroupBooking\": {"
		                		+ "\"value\":true"
		                		+ "},"
		                		+ "\"hotels\": "
		                		+ "["
		                		+ "{"
		                		+ "\"id\": \""+LoadCart.HotelID+"\","
		                		+ "\"preference\": {"
		                		+ "\"value\": \"nopreference\""
		                		+ "},"
		                		+ "\"bookings\": {"
		                		+ "\"booking\": {"
		                		+ "\"id\": \""+LoadCart.BookingID+"\","
		                		+ "\"gueststays\": "
		                		+ "["
		                		+ "{"
		                		+ "\"id\": \""+LoadCart.GuestStaysID+"\","
		                		+ "\"guest\": {"
		                		+ "\"fname\": {"
		                		+ "\"value\": \""+firstname+"\""
		                		+ " },"
		                		+ "\"lname\": {"
		                		+ "\"value\": \"upadhaya\""
		                		+ "},"
		                		+ "\"email\": {"
		                		+ "\"value\": \""+firstname+".hotelogix@stayezee.com\""
		                		+ "},"
		                		+ "\"phone\": {"
		                		+ "\"value\": \"9968040558\""
		                		+ "},"
		                		+ "\"mobile\": {"
		                		+ "\"value\": \"9968040558\""
		                		+ "},"
		                		+ "\"country\": {"
		                		+ "\"code\": \"IN\","
		                		+ "\"value\": \"India\""
		                		+ "},"
		                		+ "\"state\": {"
		                		+ "\"code\": \"br\","
		                		+ "\"value\": \"Bihar\""
		                		+ "},"
		                		+ "\"address\": {"
		                		+ "\"value\": \"mayur vihar\""
		                		+ "},"
		                		+ "\"city\": {"
		                		+ "\"value\": \"madhubani\""
		                		+ "},"
		                		+ "\"zip\": {"
		                		+ "\"value\": \"110091\""
		                		+ "},"
		                		+ "\"taxCode\": {"
		                		+ "\"value\": \"07AQSPJ0999EABC\""
		                		+ "},"
		                		+ "\"workDetail\": {"
		                		+ "\"address\": {"
		                		+ "\"value\": \"work address\""
		                		+ "},"
		                		+ "\"city\": {"
		                		+ "\"value\": \"work city\""
		                		+ "},"
		                		+ "\"state\": {"
		                		+ "\"code\": \"DE\","
		                		+ "\"value\": \"delhi\""
		                		+ "},"
		                		+ "\"country\": {"
		                		+ "\"code\": \"IN\","
		                		+ "\"value\": \"India\""
		                		+ "},"
		                		+ "\"zip\": {"
		                		+ "\"value\": \"110096\""
		                		+ "},"
		                		+ "\"phone\": {"
		                		+ "\"value\": \"123456789\""
		                		+ "},"
		                		+ "\"mobile\": {"
		                		+ "\"value\": \"123456789\""
		                		+ "},"
		                		+ "\"fax\": {"
		                		+ "\"value\": \"123456789\""
		                		+ "}}}}],"
		                		+ "\"infantstays\": ["
		                		+ "{"
		                		+ "\"id\": \""+LoadCart.InfantID+"\","
		                		+ "\"infant\": {"
		                		+ "\"salutation\": {"
		                		+ "\"value\": \"Mr.\""
		                		+ "},"
		                		+ "\"fname\": {"
		                		+ "\"value\": \"shubham\""
		                		+ " },"
		                		+ "\"lname\": {"
		                		+ "\"value\": \"kumar\""
		                		+ "},"
		                		+ "\"dob\": {"
		                		+ "\"value\": \"2017-08-06 00:00:00\""
		                		+ "}}}]}}}]}}}}")
		                .asJson();
			 JsonNode responseJSONString=response.getBody();
			 Assert.assertEquals(response.getCode(), 200);
			 JSONObject jobj=responseJSONString.getObject();
			 JSONObject hotelogix= jobj.getJSONObject("hotelogix");
			 JSONObject respons=hotelogix.getJSONObject("response");
			 JSONObject order=respons.getJSONObject("order");
			 JSONObject deposittotal=order.getJSONObject("deposittotal");
			 DepositTotal=deposittotal.get("amount").toString();
			 JSONObject orderamount=order.getJSONObject("orderamount");
			 OrderAmount=orderamount.get("amount").toString();
			 JSONObject bookings=order.getJSONArray("bookings").getJSONObject(0);
			 JSONObject rates=bookings.getJSONArray("rates").getJSONObject(0);
			 JSONObject cancellationpolicies=rates.getJSONArray("cancellationpolicies").getJSONObject(0);
			 CancellationCharge=cancellationpolicies.get("charge").toString();
			 OrderID=order.get("id").toString();
			 JSONObject status= respons.getJSONObject("status");
			 Assert.assertEquals(status.getString("message"), "SUCCESS");
	  }catch(Throwable e){
		  throw new APIException("fn_SaveBooking api is failed", e);	
	  }
	}
	
	
	
	public void fn_SaveBookingForRateIdforaddtocartapi(String url,String wsauth,String firstname,String email) throws APIException{
		try{
			 HttpResponse<JsonNode> response = Unirest.post(url)
		                .header("content-type", "application/json")
		                .header("x-ig-sg", "D_gg%fkl85_j")
		                .header("cache-control", "no-cache")
		                .header("postman-token", "586c8072-4a88-dff1-cb04-294c764db5d7")
		                .body("{ \"hotelogix\": {"
		                		+ "\"version\": \"1.0\","
		                		+ "\"datetime\": \"2015-09-16T11:01:29\","
		                		+ " \"request\": {"
		                		+ " \"method\": \"savebooking\","
		                		+ "\"key\": \""+wsauth+"\","
		                		+ "\"languagecode\" :\"en\","
		                		+ "\"data\": {"
		                		+ "\"guest\": {"
		                		+ "\"fname\": {"
		                		+ "\"value\": \""+firstname+"\""
		                		+ "},"
		                		+ "\"lname\": {"
		                		+ "\"value\": \"Jha\""
		                		+ " },"
		                		+ "\"email\": {"
		                		+ "\"value\": \""+firstname+".hotelogix@stayezee.com\""
		                		+ " },"
		                		+ "\"phone\": {"
		                		+ "\"value\": \"2121221212121\""
		                		+ " },"
		                		+ "\"mobile\": {"
		                		+ "\"value\": \"988888989\""
		                		+ "},"
		                		+ "\"country\": {"
		                		+ "\"code\": \"IN\","
		                		+ "\"value\": \"India\""
		                		+ " },"
		                		+ "\"state\": {"
		                		+ "\"code\": \"UP\","
		                		+ "\"value\": \"noida\""
		                		+ " },"
		                		+ "\"address\": {"
		                		+ " \"value\": \"test address\""
		                		+ " },"
		                		+ "\"city\": {"
		                		+ "\"value\": \"noida\""
		                		+ " },"
		                		+ "\"zip\": {"
		                		+ "\"value\": \"12345A\""
		                		+ " },"
		                		+ "\"taxCode\": {"
		                		+ "\"value\": \"07AQSPJ0999EABC\""
		                		+ "},"
		                		+ "\"workDetail\": {"
		                		+ "\"address\": {"
		                		+ "\"value\": \"work address\""
		                		+ " },"
		                		+ "\"city\": {"
		                		+ "\"value\": \"work city\""
		                		+ "},"
		                		+ "\"state\": {"
		                		+ "\"code\": \"DE\","
		                		+ "\"value\": \"delhi\""
		                		+ " },"
		                		+ "\"country\": {"
		                		+ "\"code\": \"IN\","
		                		+ "\"value\": \"India\""
		                		+ "},"
		                		+ "\"zip\": {"
		                		+ "\"value\": \"110096\""
		                		+ "},"
		                		+ "\"phone\": {"
		                		+ "\"value\": \"123456789\""
		                		+ " },"
		                		+ "\"mobile\": {"
		                		+ "\"value\": \"123456789\""
		                		+ "},"
		                		+ "\"fax\": {"
		                		+ "\"value\": \"123456789\""
		                		+ "}"
		                		+ "}"
		                		+ "},"
		                		+ "\"isGroupBooking\": {"
		                		+ "\"value\":false"
		                		+ "},"
		                		+ "\"hotels\": "
		                		+ "["
		                		+ "{"
		                		+ "\"id\": \""+LoadCart.HotelID+"\","
		                		+ "\"preference\": {"
		                		+ "\"value\": \"nopreference\""
		                		+ "},"
		                		+ "\"bookings\": {"
		                		+ "\"booking\": {"
		                		+ "\"id\": \""+LoadCart.BookingID+"\","
		                		+ "\"gueststays\": "
		                		+ "["
		                		+ "{"
		                		+ "\"id\": \""+LoadCart.GuestStaysID+"\","
		                		+ "\"guest\": {"
		                		+ "\"fname\": {"
		                		+ "\"value\": \""+firstname+"\""
		                		+ " },"
		                		+ "\"lname\": {"
		                		+ "\"value\": \"upadhaya\""
		                		+ "},"
		                		+ "\"email\": {"
		                		+ "\"value\": \""+firstname+".hotelogix@stayezee.com\""
		                		+ "},"
		                		+ "\"phone\": {"
		                		+ "\"value\": \"9968040558\""
		                		+ "},"
		                		+ "\"mobile\": {"
		                		+ "\"value\": \"9968040558\""
		                		+ "},"
		                		+ "\"country\": {"
		                		+ "\"code\": \"IN\","
		                		+ "\"value\": \"India\""
		                		+ "},"
		                		+ "\"state\": {"
		                		+ "\"code\": \"br\","
		                		+ "\"value\": \"Bihar\""
		                		+ "},"
		                		+ "\"address\": {"
		                		+ "\"value\": \"mayur vihar\""
		                		+ "},"
		                		+ "\"city\": {"
		                		+ "\"value\": \"madhubani\""
		                		+ "},"
		                		+ "\"zip\": {"
		                		+ "\"value\": \"110091\""
		                		+ "},"
		                		+ "\"taxCode\": {"
		                		+ "\"value\": \"07AQSPJ0999EABC\""
		                		+ "},"
		                		+ "\"workDetail\": {"
		                		+ "\"address\": {"
		                		+ "\"value\": \"work address\""
		                		+ "},"
		                		+ "\"city\": {"
		                		+ "\"value\": \"work city\""
		                		+ "},"
		                		+ "\"state\": {"
		                		+ "\"code\": \"DE\","
		                		+ "\"value\": \"delhi\""
		                		+ "},"
		                		+ "\"country\": {"
		                		+ "\"code\": \"IN\","
		                		+ "\"value\": \"India\""
		                		+ "},"
		                		+ "\"zip\": {"
		                		+ "\"value\": \"110096\""
		                		+ "},"
		                		+ "\"phone\": {"
		                		+ "\"value\": \"123456789\""
		                		+ "},"
		                		+ "\"mobile\": {"
		                		+ "\"value\": \"123456789\""
		                		+ "},"
		                		+ "\"fax\": {"
		                		+ "\"value\": \"123456789\""
		                		+ "}}}}]"
		                		+ "}"
		                		+ "}"
		                		+ "}"
		                		+ "]"
		                		+ "}"
		                		+ "}"
		                		+ "}"
		                		+ "}")
		                .asJson();
			 JsonNode responseJSONString=response.getBody();
			 Assert.assertEquals(response.getCode(), 200);
			 JSONObject jobj=responseJSONString.getObject();
			 JSONObject hotelogix= jobj.getJSONObject("hotelogix");
			 JSONObject respons=hotelogix.getJSONObject("response");
			 JSONObject order=respons.getJSONObject("order");
			 JSONObject orderamount=order.getJSONObject("orderamount");
			 OrderAmount=orderamount.get("amount").toString();
			 JSONObject bookings=order.getJSONArray("bookings").getJSONObject(0);
			 JSONObject rates=bookings.getJSONArray("rates").getJSONObject(0);
			 JSONObject cancellationpolicies=rates.getJSONArray("cancellationpolicies").getJSONObject(0);
			 CancellationCharge=cancellationpolicies.get("charge").toString();
			 OrderID=order.get("id").toString();
			 JSONObject status= respons.getJSONObject("status");
			 Assert.assertEquals(status.getString("message"), "SUCCESS");
	  }catch(Throwable e){
		  throw new APIException("SaveBookingForRateIdforaddtocartapi api is failed", e);	
	  }
	}
	
	

	public void fn_SaveBooking(String url, String loginaccesskey,String firstname,String email,String hotelID,String bookingID,String guestID) throws APIException{
		
		try{
			 HttpResponse<JsonNode> response = Unirest.post(url)
		                .header("content-type", "application/json")
		                .header("x-ig-sg", "D_gg%fkl85_j")
		                .header("cache-control", "no-cache")
		                .header("postman-token", "586c8072-4a88-dff1-cb04-294c764db5d7")
		                .body("{ \"hotelogix\": {"
                                + "\"version\": \"1.0\","
                                + "\"datetime\": \"2015-09-16T11:01:29\","
                                + " \"request\": {"
                                + " \"method\": \"savebooking\","
                                + "\"key\": \""+loginaccesskey+"\","
                                + "\"languagecode\" :\"en\","
                                + "\"data\": {"
                                + "\"guest\": {"
                                + "\"fname\": {"
                                + "\"value\": \""+firstname+"\""
                                + "},"
                                + "\"lname\": {"
                                + "\"value\": \"Jha\""
                                + " },"
                                + "\"email\": {"
                                + "\"value\": \""+firstname+".hotelogix@stayezee.com\""
                                + " },"
                                + "\"phone\": {"
                                + "\"value\": \"2121221212121\""
                                + " },"
                                + "\"mobile\": {"
                                + "\"value\": \"988888989\""
                                + "},"
                                + "\"country\": {"
                                + "\"code\": \"IN\","
                                + "\"value\": \"India\""
                                + " },"
                                + "\"state\": {"
                                + "\"code\": \"UP\","
                                + "\"value\": \"noida\""
                                + " },"
                                + "\"address\": {"
                                + " \"value\": \"test address\""
                                + " },"
                                + "\"city\": {"
                                + "\"value\": \"noida\""
                                + " },"
                                + "\"zip\": {"
                                + "\"value\": \"12345A\""
                                + " },"
                                + "\"taxCode\": {"
                                + "\"value\": \"07AQSPJ0999EABC\""
                                + "},"
                                + "\"workDetail\": {"
                                + "\"address\": {"
                                + "\"value\": \"work address\""
                                + " },"
                                + "\"city\": {"
                                + "\"value\": \"work city\""
                                + "},"
                                + "\"state\": {"
                                + "\"code\": \"DE\","
                                + "\"value\": \"delhi\""
                                + " },"
                                + "\"country\": {"
                                + "\"code\": \"IN\","
                                + "\"value\": \"India\""
                                + "},"
                                + "\"zip\": {"
                                + "\"value\": \"110096\""
                                + "},"
                                + "\"phone\": {"
                                + "\"value\": \"123456789\""
                                + " },"
                                + "\"mobile\": {"
                                + "\"value\": \"123456789\""
                                + "},"
                                + "\"fax\": {"
                                + "\"value\": \"123456789\""
                                + "}"
                                + "}"
                                + "},"
                                + "\"isGroupBooking\": {"
                                + "\"value\":false"
                                + "},"
                                + "\"hotels\": "
                                + "["
                                + "{"
                                + "\"id\": \""+hotelID+"\","
                                + "\"preference\": {"
                                + "\"value\": \"nopreference\""
                                + "},"
                                + "\"bookings\": {"
                                + "\"booking\": {"
                                + "\"id\": \""+bookingID+"\","
                                + "\"gueststays\": "
                                + "["
                                + "{"
                                + "\"id\": \""+guestID+"\","
                                + "\"guest\": {"
                                + "\"fname\": {"
                                + "\"value\": \""+firstname+"\""
                                + " },"
                                + "\"lname\": {"
                                + "\"value\": \"upadhaya\""
                                + "},"
                                + "\"email\": {"
                                + "\"value\": \""+firstname+".hotelogix@stayezee.com\""
                                + "},"
                                + "\"phone\": {"
                                + "\"value\": \"9968040558\""
                                + "},"
                                + "\"mobile\": {"
                                + "\"value\": \"9968040558\""
                                + "},"
                                + "\"country\": {"
                                + "\"code\": \"IN\","
                                + "\"value\": \"India\""
                                + "},"
                                + "\"state\": {"
                                + "\"code\": \"br\","
                                + "\"value\": \"Bihar\""
                                + "},"
                                + "\"address\": {"
                                + "\"value\": \"mayur vihar\""
                                + "},"
                                + "\"city\": {"
                                + "\"value\": \"madhubani\""
                                + "},"
                                + "\"zip\": {"
                                + "\"value\": \"110091\""
                                + "},"
                                + "\"taxCode\": {"
                                + "\"value\": \"07AQSPJ0999EABC\""
                                + "},"
                                + "\"workDetail\": {"
                                + "\"address\": {"
                                + "\"value\": \"work address\""
                                + "},"
                                + "\"city\": {"
                                + "\"value\": \"work city\""
                                + "},"
                                + "\"state\": {"
                                + "\"code\": \"DE\","
                                + "\"value\": \"delhi\""
                                + "},"
                                + "\"country\": {"
                                + "\"code\": \"IN\","
                                + "\"value\": \"India\""
                                + "},"
                                + "\"zip\": {"
                                + "\"value\": \"110096\""
                                + "},"
                                + "\"phone\": {"
                                + "\"value\": \"123456789\""
                                + "},"
                                + "\"mobile\": {"
                                + "\"value\": \"123456789\""
                                + "},"
                                + "\"fax\": {"
                                + "\"value\": \"123456789\""
                                + "}}}}]"
                                + "}}}]}}}}")
		                     .asJson();
			 JsonNode responseJSONString=response.getBody();
			 Assert.assertEquals(response.getCode(), 200);
			 String str=responseJSONString.toString();
			 JSONObject jobj=new JSONObject(str);
			 JSONObject hotelogix= jobj.getJSONObject("hotelogix");
			 JSONObject respons=hotelogix.getJSONObject("response");
			 JSONObject status= respons.getJSONObject("status");
			 Assert.assertEquals(status.getString("message"), "SUCCESS");
			 JSONObject order=respons.getJSONObject("order");
             OrderID=order.get("id").toString();
	  }catch(Throwable e){
		  throw new APIException("fn_SaveBooking api is failed", e);	
	  }
	}
	
	
	
	public void fn_SaveBookingAPIForGrp(String URL,String loginaccesskey,String firstname,String email,String hotelID,String bookingID,String guestID) throws APIException{
		try{
			 HttpResponse<JsonNode> response = Unirest.post(URL)
		                .header("content-type", "application/json")
		                .header("x-ig-sg", "D_gg%fkl85_j")
		                .header("cache-control", "no-cache")
		                .header("postman-token", "586c8072-4a88-dff1-cb04-294c764db5d7")
		                .body("{"
		                		+ "\"hotelogix\": {"
		                		+ "\"version\": \"1.0\","
		                		+ "\"datetime\": \"2012-01-16T10:10:15\","
		                		+ "\"request\": {"
		                		+ "\"method\": \"savebooking\","
		                		+ "\"key\": \""+loginaccesskey+"\","		                	
		                		+ "\"languagecode\": \"en\","
		                		+ "\"data\": {"
		                		+ "\"guest\": {"
		                		+ "\"fname\": {"
		                		+ "\"value\": \""+firstname+"\""
		                		+ "},"
		                		+ "\"lname\": {"
		                		+ "\"value\": \"kapoor\""
		                		+ "},"
		                		+ "\"email\": {"
		                		+ "\"value\": \""+email+"@hotelogix.com\""
		                		+ "},"
		                		+ "\"phone\": {"
		                		+ "\"value\": \"2121221212121\""
		                		+ "},"
		                		+ "\"mobile\": {"
		                		+ "\"value\": \"988888989\""
		                		+ "},"
		                		+ "\"country\": {"
		                		+ "\"code\": \"IN\","
		                		+ "\"value\": \"India\""
		                		+ "},"
		                		+ "\"state\": {"
		                		+ "\"code\": \"UP\","
		                		+ "\"value\": \"noida\""
		                		+ "},"
		                		+ "\"address\": {"
		                		+ "\"value\": \"test address\""
		                		+ "},"
		                		+ "\"city\": {"
		                		+ "\"value\": \"noida\""
		                		+ "},"
		                		+ "\"zip\": {"
		                		+ "\"value\": \"12345A\""
		                		+ "},"
		                		+ "\"taxCode\": {"
		                		+ "\"value\": \"07AQSPJ0999EABC\""
		                		+ "},"
		                		+ "\"workDetail\": {"
		                		+ "\"address\": {"
		                		+ "\"value\": \"work address\""
		                		+ "},"
		                		+ "\"city\": {"
		                		+ "\"value\": \"work city\""
		                		+ "},"
		                		+ "\"state\": {"
		                		+ "\"code\": \"DE\","
		                		+ "\"value\": \"delhi\""
		                		+ "},"
		                		+ "\"country\": {"
		                		+ "\"code\": \"IN\","
		                		+ "\"value\": \"India\""
		                		+ "},"
		                		+ "\"zip\": {"
		                		+ "\"value\": \"zip\""
		                		+ "},"
		                		+ "\"phone\": {"
		                		+ "\"value\": \"123456789\""
		                		+ "},"
		                		+ "\"mobile\": {"
		                		+ "\"value\": \"123456789\""
		                		+ "},"
		                		+ "\"fax\": {"
		                		+ "\"value\": \"123456789\""
		                		+ "}}},"
		                		+ "\"isGroupBooking\": {"
		                		+ "\"value\":true"
		                		+ "},"
		                		+ "\"hotels\": ["
		                		+ "{"
		                		+ "\"id\": \""+hotelID+"\","
		                		+ "\"preference\": {"
		                		+ "\"value\": \"nopreference\""
		                		+ "},"
		                		+ "\"bookings\": {"
		                		+ "\"booking\": {"
		                		+ "\"id\": \""+bookingID+"\","
		                		+ "\"gueststays\": ["
		                		+ "{"
		                		+ "\"id\": \""+guestID+"\","
		                		+ "\"guest\": {"
		                		+ "\"fname\": {"
		                		+ "\"value\": \"Vandana\""
		                		+ "},"
		                		+ "\"lname\": {"
		                		+ "\"value\": \"upadhaya\""
		                		+ "},"
		                		+ "\"email\": {"
		                		+ "\"value\": \""+email+"@hotelogix.com\""
		                		+ "},"
		                		+ "\"phone\": {"
		                		+ "\"value\": \"9968040558\""
		                		+ "},"
		                		+ "\"mobile\": {"
		                		+ "\"value\": \"9968040558\""
		                		+ "},"
		                		+ "\"country\": {"
		                		+ "\"code\": \"IN\","
		                		+ "\"value\": \"India\""
		                		+ "},"
		                		+ "\"state\": {"
		                		+ "\"code\": \"br\","
		                		+ "\"value\": \"Bihar\""
		                		+ "},"
		                		+ "\"address\": {"
		                		+ "\"value\": \"mayur vihar\""
		                		+ "},"
		                		+ "\"city\": {"
		                		+ "\"value\": \"madhubani\""
		                		+ "},"
		                		+ "\"zip\": {"
		                		+ "\"value\": \"110091\""
		                		+ "},"
		                		+ "\"taxCode\": {"
		                		+ "\"value\": \"07AQSPJ0999EABC\""
		                		+ "},"
		                		+ "\"workDetail\": {"
		                		+ "\"address\": {"
		                		+ "\"value\": \"work address\""
		                		+ "},"
		                		+ "\"city\": {"
		                		+ "\"value\": \"work city\""
		                		+ "},"
		                		+ "\"state\": {"
		                		+ "\"code\": \"DE\","
		                		+ "\"value\": \"delhi\""
		                		+ "},"
		                		+ "\"country\": {"
		                		+ "\"code\": \"IN\","
		                		+ "\"value\": \"India\""
		                		+ "},"
		                		+ "\"zip\": {"
		                		+ "\"value\": \"zip\""
		                		+ "},"
		                		+ "\"phone\": {"
		                		+ "\"value\": \"123456789\""
		                		+ "},"
		                		+ "\"mobile\": {"
		                		+ "\"value\": \"123456789\""
		                		+ "},"
		                		+ "\"fax\": {"
		                		+ "\"value\": \"123456789\""
		                		+ "}}}}]"
		                		+ "}}}]}}}}")
		                     .asJson();
			 JsonNode responseJSONString=response.getBody();
			 Assert.assertEquals(response.getCode(), 200);
			 String str=responseJSONString.toString();
			 JSONObject jobj=new JSONObject(str);
			 JSONObject hotelogix= jobj.getJSONObject("hotelogix");
			 JSONObject respons=hotelogix.getJSONObject("response");
			 JSONObject status= respons.getJSONObject("status");
			 Assert.assertEquals(status.getString("message"), "SUCCESS");
			 JSONObject order1=respons.getJSONObject("order");
             OrderID=order1.get("id").toString();
             JSONArray bkgarr=order1.getJSONArray("bookings");
             JSONObject bkgObj= bkgarr.getJSONObject(0);
             String bkgID=bkgObj.get("id").toString();
             Assert.assertEquals(bkgID.equals(bookingID), true,"Booking ID of reservation didn't matched.");
             JSONObject amt=order1.getJSONObject("deposittotal");
             depositAmt=amt.get("amount").toString();
		}catch(Throwable e){
			throw new APIException("fn_SaveBookingAPIForGrp has failed", e);
		}
	}
	
	
}
